export default [
  {
    name: "Quinoa Salad",
    shop: "",
    calories: 300,
    envStars: 5,
  },
  { name: "Chicken Breast", shop: "", calories: 200, envStars: 4 },
  {
    name: "Chicken Teriyakai Burger",
    shop: "Mos Burger",
    calories: 420,
    envStars: 3,
  },
  {
    name: "Beef Bolognese",
    shop: "Pasta Mania",
    calories: 580,
    envStars: 2,
  },
  {
    name: "McSpicy",
    shop: "Mcdonald's",
    calories: 650,
    envStars: 2,
  },
  {
    name: "Avocado Milkshake",
    shop: "",
    calories: 350,
    envStars: 4,
  },
  {
    name: "Cold Brew",
    shop: "Starbucks",
    calories: 0,
    envStars: 3,
  },
  {
    name: "Fish Head Curry",
    shop: "Pooth",
    calories: 750,
    envStars: 2,
  },
  {
    name: "Quinoa Salad",
    shop: "",
    calories: 300,
    envStars: 5,
  },
  { name: "Chicken Breast", shop: "", calories: 200, envStars: 4 },
  {
    name: "Chicken Teriyakai Burger",
    shop: "Mos Burger",
    calories: 420,
    envStars: 3,
  },
  {
    name: "Beef Bolognese",
    shop: "Pasta Mania",
    calories: 580,
    envStars: 2,
  },
  {
    name: "McSpicy",
    shop: "Mcdonald's",
    calories: 650,
    envStars: 2,
  },
  {
    name: "Avocado Milkshake",
    shop: "",
    calories: 350,
    envStars: 4,
  },
  {
    name: "Cold Brew",
    shop: "Starbucks",
    calories: 0,
    envStars: 3,
  },
  {
    name: "Fish Head Curry",
    shop: "Pooth",
    calories: 750,
    envStars: 2,
  },
];
